version: "3.8"
services:
  frontend:
    build: frontend
    ports: 
      - 8080:8080
  backend:
    build: backend
    environment:
        MONGODB_CONNECTION_STRING: "mongodb://database/kurzarbeit"
    ports: 
      - 4000:4000
  database:
    image: mongo:4.2 
    ports:
      - 37017:27017   
    volumes: 
      - ./data:/data/db  